[versions]
agp = '9.3.1'

curl = "7.79.1-beta-1"
googletest = "1.11.0-beta-1"
jsoncpp = "1.9.5-beta-1"
openssl = "1.1.1q-beta-1"

[libraries]
curl = { group = "com.android.ndk.thirdparty", name = "curl", version.ref = "curl" }
googletest = { group = "com.android.ndk.thirdparty", name = "googletest", version.ref = "googletest" }
jsoncpp = { group = "com.android.ndk.thirdparty", name = "jsoncpp", version.ref = "jsoncpp" }
openssl = { group = "com.android.ndk.thirdparty", name = "openssl", version.ref = "openssl" }

[plugins]
application = { id = 'com.android.application', version.ref = 'agp' }
library = { id = 'com.android.library', version.ref = 'agp' }


